# Generated by Django 6.0.7 on 2026-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('education', 'Education'), ('wellness', 'Wellness'), ('support', 'Support'), ('volunteer', 'Volunteer')], max_length=20)),
                ('emoji', models.CharField(blank=True, help_text='Small emoji shown next to the title, e.g. 🎓', max_length=8)),
                ('summary', models.CharField(help_text='One-line description shown on cards.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Optional longer detail shown on the Resources page.')),
                ('external_link', models.URLField(blank=True, help_text='Optional link to an external resource.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SunshineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this entry is meant for.', unique=True)),
                ('quote', models.CharField(max_length=300)),
                ('meaning', models.TextField(help_text='What the quote means, in plain language.')),
                ('reminder', models.CharField(help_text='A short, actionable reminder for today.', max_length=200)),
                ('affirmation', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sunshine entry',
                'verbose_name_plural': 'Sunshine entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the <title> tag. Leave blank to auto-generate. Aim for 50-60 characters.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Leave blank to auto-generate. Aim for 120-160 characters.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Optional, comma-separated. Modern search engines mostly ignore this, kept for completeness.', max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('date', models.DateField(help_text='Date the activity took place.')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('summary', models.CharField(help_text='Short teaser shown on the timeline list.', max_length=220)),
                ('body', models.TextField(help_text='Full write-up shown on the detail page.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='work/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work entry',
                'verbose_name_plural': 'Work entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
